services:
  - type: web
    name: tgconnect
    env: python
    buildCommand: "chmod +x deploy_script.sh && ./deploy_script.sh"
    startCommand: "gunicorn TGConnect.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: TGConnect.settings
      - key: PYTHON_VERSION
        value: 3.11.4
