# Generated by Django 5.2.1 on 2025-07-25 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TGConnect', '0001_initial'),
    ]

    operations = [
        # Rename tables from custom names to Django default names
        migrations.RunSQL(
            "ALTER TABLE IF EXISTS \"TGConnect_register\" RENAME TO \"TGConnect_register_new\";",
            reverse_sql="ALTER TABLE IF EXISTS \"TGConnect_register_new\" RENAME TO \"TGConnect_register\";"
        ),
        migrations.RunSQL(
            "ALTER TABLE IF EXISTS \"TGConnect_registertg\" RENAME TO \"TGConnect_registertg_new\";",
            reverse_sql="ALTER TABLE IF EXISTS \"TGConnect_registertg_new\" RENAME TO \"TGConnect_registertg\";"
        ),
        migrations.RunSQL(
            "ALTER TABLE IF EXISTS \"TGConnect_addreports\" RENAME TO \"TGConnect_addreports_new\";",
            reverse_sql="ALTER TABLE IF EXISTS \"TGConnect_addreports_new\" RENAME TO \"TGConnect_addreports\";"
        ),
        migrations.RunSQL(
            "ALTER TABLE IF EXISTS \"TGConnect_timetable\" RENAME TO \"TGConnect_timetable_new\";",
            reverse_sql="ALTER TABLE IF EXISTS \"TGConnect_timetable_new\" RENAME TO \"TGConnect_timetable\";"
        ),
        migrations.RunSQL(
            "ALTER TABLE IF EXISTS \"TGConnect_notes\" RENAME TO \"TGConnect_notes_new\";",
            reverse_sql="ALTER TABLE IF EXISTS \"TGConnect_notes_new\" RENAME TO \"TGConnect_notes\";"
        ),
        migrations.RunSQL(
            "ALTER TABLE IF EXISTS \"TGConnect_uploadassignment\" RENAME TO \"TGConnect_uploadassignment_new\";",
            reverse_sql="ALTER TABLE IF EXISTS \"TGConnect_uploadassignment_new\" RENAME TO \"TGConnect_uploadassignment\";"
        ),
        migrations.RunSQL(
            "ALTER TABLE IF EXISTS \"TGConnect_attendance\" RENAME TO \"TGConnect_attendance_new\";",
            reverse_sql="ALTER TABLE IF EXISTS \"TGConnect_attendance_new\" RENAME TO \"TGConnect_attendance\";"
        ),
        migrations.RunSQL(
            "ALTER TABLE IF EXISTS \"TGConnect_notification\" RENAME TO \"TGConnect_notification_new\";",
            reverse_sql="ALTER TABLE IF EXISTS \"TGConnect_notification_new\" RENAME TO \"TGConnect_notification\";"
        ),
    ]
