# Generated by Django 5.2.1 on 2025-07-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TGConnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addreports',
            table='TGConnect_addreports',
        ),
        migrations.AlterModelTable(
            name='attendance',
            table='TGConnect_attendance',
        ),
        migrations.AlterModelTable(
            name='notes',
            table='TGConnect_notes',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='TGConnect_notification',
        ),
        migrations.AlterModelTable(
            name='register',
            table='TGConnect_register',
        ),
        migrations.AlterModelTable(
            name='registertg',
            table='TGConnect_registertg',
        ),
        migrations.AlterModelTable(
            name='timetable',
            table='TGConnect_timetable',
        ),
        migrations.AlterModelTable(
            name='uploadassignment',
            table='TGConnect_uploadassignment',
        ),
    ]
