# Generated by Django 5.2.1 on 2025-07-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGConnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreports',
            name='enroll',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='enroll',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='registertg',
            name='department',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='registertg',
            name='id',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='registertg',
            name='mobile',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='uploadassignment',
            name='enroll',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
    ]
