# Generated by Django 5.2.1 on 2025-05-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGConnect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addreports',
            fields=[
                ('enroll', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('sem', models.IntegerField(max_length=1)),
                ('cgpa', models.FloatField()),
                ('filename', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='enroll',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.IntegerField(unique=True),
        ),
    ]
