# Generated by Django 5.2.1 on 2025-05-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGConnect', '0002_addreports_alter_register_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='gender',
            field=models.CharField(default='Not Specified'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addreports',
            name='sem',
            field=models.IntegerField(),
        ),
    ]
