# Generated by Django 5.2.1 on 2025-05-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGConnect', '0003_register_gender_alter_addreports_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='addreports',
            name='branch',
            field=models.CharField(default='Not Specified', max_length=20),
            preserve_default=False,
        ),
    ]
