# Generated by Django 5.2.1 on 2025-05-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGConnect', '0004_addreports_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterTG',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.IntegerField(unique=True)),
                ('course', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('status', models.IntegerField()),
                ('role', models.CharField(max_length=10)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
