# Generated by Django 5.2.1 on 2025-05-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGConnect', '0005_registertg_alter_register_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('department', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=10)),
                ('week', models.CharField(max_length=10)),
                ('fromdate', models.CharField(max_length=20)),
                ('todate', models.CharField(max_length=20)),
                ('filename', models.CharField(max_length=20)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
    ]
