# Generated by Django 5.2.1 on 2025-05-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGConnect', '0006_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='timetable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='department',
            field=models.CharField(max_length=20),
        ),
    ]
