# Generated by Django 5.2.1 on 2025-05-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGConnect', '0008_alter_notes_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadAssignment',
            fields=[
                ('enroll', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=25)),
                ('filename', models.CharField(max_length=40)),
                ('verify', models.IntegerField()),
                ('info', models.CharField(max_length=45)),
            ],
        ),
    ]
