# Generated by Django 5.2.1 on 2025-07-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGConnect', '0011_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreports',
            name='enroll',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='enroll',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='registertg',
            name='department',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='registertg',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='registertg',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadassignment',
            name='enroll',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
