# Generated by Django 5.2.1 on 2025-07-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGConnect', '0012_alter_addreports_enroll_alter_register_enroll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='registertg',
            name='department',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registertg',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
