# Generated by Django 5.2.1 on 2025-07-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGConnect', '0013_alter_register_mobile_alter_registertg_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
