# Generated by Django 5.2.1 on 2025-07-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGConnect', '0013_alter_register_mobile_alter_registertg_department_and_more'),
    ]

    operations = [
        # Drop and recreate TimeTable model to fix primary key issues
        migrations.RunSQL(
            "DROP TABLE IF EXISTS TGConnect_timetable CASCADE;",
            reverse_sql="SELECT 1;"  # Dummy reverse SQL
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('department', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=10)),
                ('week', models.CharField(max_length=10)),
                ('fromdate', models.CharField(max_length=20)),
                ('todate', models.CharField(max_length=20)),
                ('filename', models.CharField(max_length=20)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
    ]
